services:
  clientmanager:
    container_name: ClientManager
    build:
      context: ./ClientManager
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - kafka

  coffeemaker:
    container_name: CoffeeMaker
    build:
      context: ./CoffeeMaker
      dockerfile: Dockerfile
    depends_on:
      - kafka

  kafka:
    image: confluentinc/cp-kafka:7.6.0
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
        CLUSTER_ID: 'i6B8hlxLSi2S_OMgfH1XNQ'
        KAFKA_NODE_ID: 1
        KAFKA_PROCESS_ROLES: broker,controller
        KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
        KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
        KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
        KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
        KAFKA_LOG4J_ROOT_LOGLEVEL: WARN

